=== derekpk/JaxbAndXsd/JaxbAndXsd/src/resources/Grid.xsd
<?xml version="1.0" encoding="UTF-8"?>
<dk:schema  xmlns:dk="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.decoder.ie/namespaces"
            targetNamespace="http://www.decoder.ie/namespaces"
            elementFormDefault="qualified"
            attributeFormDefault="qualified">

	<dk:element name="grid">
	    <dk:complexType>
	        <dk:sequence>
	            <dk:element name="XbyY" minOccurs="1" maxOccurs="1">
	                <dk:complexType>
			            <dk:attributeGroup ref="gridAttributes"/>
			        </dk:complexType>
                </dk:element>

                <dk:element name="cell" minOccurs="81" maxOccurs="81">
			        <dk:complexType>
			            <dk:sequence>
			                <dk:element name="Value" type="ZeroToNine" minOccurs="1" maxOccurs="1" default="0"/>
			            </dk:sequence>
			            <dk:attributeGroup ref="cellAttributes"/>
			        </dk:complexType>
                </dk:element>

	        </dk:sequence>
	    </dk:complexType>
    </dk:element>
	
    <dk:attributeGroup name="gridAttributes">
        <dk:attribute name="width" type="dk:int" use="required"/>
        <dk:attribute name="length" type="dk:int" use="required"/>
    </dk:attributeGroup>

    <dk:attributeGroup name="cellAttributes">
        <dk:attribute name="X" type="ZeroToNine" use="required"/>
        <dk:attribute name="Y" type="ZeroToNine" use="required"/>
        <dk:attribute name="index" type="ZeroToEightyone" use="required"/>
    </dk:attributeGroup>

    <!-- Restrict values using ENUM -->
    <dk:simpleType name="ZeroToNine">
       <dk:restriction base="dk:int">
           <dk:enumeration value="0"/>
           <dk:enumeration value="1"/>
           <dk:enumeration value="2"/>
           <dk:enumeration value="3"/>
           <dk:enumeration value="4"/>
           <dk:enumeration value="5"/>
           <dk:enumeration value="6"/>
           <dk:enumeration value="7"/>
           <dk:enumeration value="8"/>
           <dk:enumeration value="9"/>
        </dk:restriction>
    </dk:simpleType>
    
    <!-- Restrict values using MIN and MAX -->
    <dk:simpleType name="ZeroToEightyone">
        <dk:restriction base="dk:integer">
            <dk:minInclusive value="0"/>
            <dk:maxInclusive value="81"/>
        </dk:restriction>
    </dk:simpleType>

</dk:schema>

=== derekpk/JaxbAndXsd/JaxbAndXsd/src/resources/Grid.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:grid xmlns:p="http://www.decoder.ie/namespaces" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.decoder.ie/namespaces Grid.xsd ">
  <p:XbyY p:length="0" p:width="0"/>
  <p:cell p:X="0" p:Y="1" p:index="0">
    <p:Value>1</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="2" p:index="1">
    <p:Value>2</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="3" p:index="2">
    <p:Value>3</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="4" p:index="3">
    <p:Value>4</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="5" p:index="4">
    <p:Value>5</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="6" p:index="5">
    <p:Value>6</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="7" p:index="6">
    <p:Value>7</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="8" p:index="7">
    <p:Value>8</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="9" p:index="8">
    <p:Value>9</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="9">
    <p:Value>4</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="10">
    <p:Value>5</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="11">
    <p:Value>6</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="12">
    <p:Value>7</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="13">
    <p:Value>8</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="14">
    <p:Value>9</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="15">
    <p:Value>1</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="16">
    <p:Value>2</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="17">
    <p:Value>3</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="18">
    <p:Value>7</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="19">
    <p:Value>8</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="20">
    <p:Value>9</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="21">
    <p:Value>1</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="22">
    <p:Value>2</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="23">
    <p:Value>3</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="24">
    <p:Value>4</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="25">
    <p:Value>5</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="26">
    <p:Value>6</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="27">
    <p:Value>2</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="28">
    <p:Value>3</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="29">
    <p:Value>4</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="30">
    <p:Value>5</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="31">
    <p:Value>6</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="32">
    <p:Value>7</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="33">
    <p:Value>8</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="34">
    <p:Value>9</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="35">
    <p:Value>1</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="36">
    <p:Value>5</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="37">
    <p:Value>6</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="38">
    <p:Value>7</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="39">
    <p:Value>8</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="40">
    <p:Value>9</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="41">
    <p:Value>1</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="42">
    <p:Value>2</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="43">
    <p:Value>3</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="44">
    <p:Value>4</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="45">
    <p:Value>8</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="46">
    <p:Value>9</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="47">
    <p:Value>1</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="48">
    <p:Value>2</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="49">
    <p:Value>3</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="50">
    <p:Value>4</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="51">
    <p:Value>5</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="52">
    <p:Value>6</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="53">
    <p:Value>7</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="54">
    <p:Value>6</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="55">
    <p:Value>7</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="56">
    <p:Value>8</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="57">
    <p:Value>9</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="58">
    <p:Value>1</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="59">
    <p:Value>2</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="60">
    <p:Value>3</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="61">
    <p:Value>4</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="62">
    <p:Value>5</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="63">
    <p:Value>3</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="64">
    <p:Value>4</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="65">
    <p:Value>5</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="66">
    <p:Value>6</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="67">
    <p:Value>7</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="68">
    <p:Value>8</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="69">
    <p:Value>9</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="70">
    <p:Value>1</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="71">
    <p:Value>2</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="72">
    <p:Value>9</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="73">
    <p:Value>1</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="74">
    <p:Value>2</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="75">
    <p:Value>3</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="76">
    <p:Value>4</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="77">
    <p:Value>5</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="78">
    <p:Value>6</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="79">
    <p:Value>7</p:Value>
  </p:cell>
  <p:cell p:X="0" p:Y="0" p:index="80">
    <p:Value>8</p:Value>
  </p:cell>
</p:grid>
